#!/bin/bash

if [ $EUID != "0" ]; then
   echo "Permission denied : This script must be run as root" ;
   exit ;
fi


echo "~~~~~~~~~~~~~~~~~~~~~~~~~~";
if ! type -p "latex" > /dev/null; then
  echo -e "Error: Install Latex  in your machine  \n pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)";
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~";

else
	echo "Checking Dependencies OK";
fi

echo "#############################";




echo "~~~~~~~~~~~~~~~~~~~~~~~~~~";
if ! type -p "rpm" > /dev/null; then
  echo -e "Error: Install rpm  in your machine ";
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~";
exit;

else
       rpm -ivh ncbi-blast-2.4.0+-2.x86_64.rpm

fi

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~";




echo "Installation process is over"; 
